# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485745d6ce0bc34bf7b26e45016d6b2c15c7ee24d1aa83a2e67ca54515b57e8b6472692531b3cfdf8d4b377b21f1452152c61cb796a3fa0daf737cdfb9e02ff4

test:
  secret_key_base: 5c224c2fea5b3c911ba788c134564c493486633d6e08c4c93811c7182517593ef3dd82f72441b7f5cd15b35338e228da35dcad7680f52182a0cace1d41f340a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
